# Generated by Django 6.0.2 on 2026-02-07 16:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('superuser', 'Superuser'), ('coordinator', 'Coordinator'), ('developer', 'Developer'), ('stakeholder', 'Stakeholder'), ('key_stakeholder', 'Key Stakeholder')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_create_users', models.BooleanField(default=False)),
                ('can_manage_projects', models.BooleanField(default=False)),
                ('can_manage_tasks', models.BooleanField(default=False)),
                ('can_move_task_stages', models.BooleanField(default=False)),
                ('can_move_task_categories', models.BooleanField(default=False)),
                ('can_reject_testing', models.BooleanField(default=False)),
                ('can_add_project_notes', models.BooleanField(default=False)),
                ('can_view_assigned_only', models.BooleanField(default=False)),
                ('can_manage_organizations', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_auto_generated', models.BooleanField(default=False, help_text='Auto-generated accounts are inactive until password reset.')),
                ('perm_create_users', models.BooleanField(blank=True, null=True)),
                ('perm_manage_projects', models.BooleanField(blank=True, null=True)),
                ('perm_manage_tasks', models.BooleanField(blank=True, null=True)),
                ('perm_move_task_stages', models.BooleanField(blank=True, null=True)),
                ('perm_move_task_categories', models.BooleanField(blank=True, null=True)),
                ('perm_reject_testing', models.BooleanField(blank=True, null=True)),
                ('perm_add_project_notes', models.BooleanField(blank=True, null=True)),
                ('perm_view_assigned_only', models.BooleanField(blank=True, null=True)),
                ('perm_manage_organizations', models.BooleanField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
