# Generated by Django 6.0.2 on 2026-02-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('coordinator', 'Coordinator'), ('developer', 'Developer')], max_length=30, unique=True),
        ),
    ]
