# Generated by Django 6.0.2 on 2026-02-09 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_name'),
        ('organizations', '0002_organization_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_organization',
            field=models.ForeignKey(blank=True, help_text='Organization this user administrates (only for Administrator role).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrators', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('system_administrator', 'System Administrator'), ('administrator', 'Administrator'), ('coordinator', 'Coordinator'), ('developer', 'Developer')], max_length=30, unique=True),
        ),
    ]
