# Generated by Django 6.0.2 on 2026-02-08 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='key_stakeholders',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stakeholders',
        ),
        migrations.AddField(
            model_name='project',
            name='commenters',
            field=models.ManyToManyField(blank=True, help_text='Can view all tasks and add comments/notes to project and tasks.', related_name='commenter_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='viewers',
            field=models.ManyToManyField(blank=True, help_text='Read-only access to view all project information.', related_name='viewer_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Full access: can edit tasks, move between stages, create tasks.', related_name='member_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
