# Generated by Django 6.0.2 on 2026-02-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_key_stakeholders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveIntegerField(default=1, help_text="Weight (1-100) used to calculate this category's contribution to project progress.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
