# Generated by Django 6.0.2 on 2026-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['order', '-created_at'], 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order of this category.'),
        ),
    ]
