# Generated by Django 6.0.2 on 2026-02-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectcategory_options_projectcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='planned_end_date',
            field=models.DateField(blank=True, help_text='Planned project completion date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_start_date',
            field=models.DateField(blank=True, help_text='Planned project start date', null=True),
        ),
    ]
