# Generated by Django 6.0.2 on 2026-02-07 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('IMPLEMENTATION', 'Implementation'), ('IMPROVEMENT', 'Improvement'), ('TESTING', 'Testing'), ('DEPLOYMENT', 'Deployment'), ('GENERAL', 'General')], default='DEVELOPMENT', max_length=20)),
                ('stage', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('HAVING_ISSUES', 'Having Issues'), ('DONE', 'Done'), ('REJECT', 'Reject')], default='TODO', max_length=20)),
                ('story_points', models.PositiveIntegerField(default=0)),
                ('points_earned', models.BooleanField(default=False, help_text='True once points are awarded.')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('original_category', models.CharField(blank=True, choices=[('DEVELOPMENT', 'Development'), ('IMPLEMENTATION', 'Implementation'), ('IMPROVEMENT', 'Improvement'), ('TESTING', 'Testing'), ('DEPLOYMENT', 'Deployment'), ('GENERAL', 'General')], help_text='Original category before cloning to testing.', max_length=20)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent_task', models.ForeignKey(blank=True, help_text='The task this was cloned from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tasks.taskinstance')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('responsible_stakeholders', models.ManyToManyField(blank=True, help_text='Stakeholders who can view this task.', related_name='responsible_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
