# Generated by Django 6.0.2 on 2026-02-08 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinstance',
            name='responsible_stakeholders',
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='assignees',
            field=models.ManyToManyField(blank=True, help_text='Users working on this task.', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
