# Generated by Django 6.0.2 on 2026-02-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectcategory'),
        ('tasks', '0003_tasknote'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='project_category',
            field=models.ForeignKey(blank=True, help_text='Project-specific category this task belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectcategory'),
        ),
    ]
