# Generated by Django 6.0.2 on 2026-02-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskinstance_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='end_date',
            field=models.DateField(blank=True, help_text='Actual task completion/end date', null=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='start_date',
            field=models.DateField(blank=True, help_text='Actual task start date', null=True),
        ),
    ]
